// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.diy.vcp.grpc.core;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
