// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.diy.vcp.grpc.core;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   * @return The sex.
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 2;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();
}
